"""Core animation assembly for GIF and MP4 outputs."""

from __future__ import annotations

import enum
import logging
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, ClassVar, cast

from PIL import Image

from ..exceptions import AssemblyError, DependencyError

if TYPE_CHECKING:
    from ..types import FrameResult

logger = logging.getLogger(__name__)


class OutputFormat(enum.Enum):
    """Supported output animation formats."""

    GIF = "gif"
    MP4 = "mp4"


class QualityPreset(enum.Enum):
    """Quality presets controlling maximum output width."""

    WEB = "web"
    PRESENTATION = "presentation"
    PRINT = "print"


QUALITY_PRESETS: dict[QualityPreset, dict[str, int]] = {
    QualityPreset.WEB: {"max_width": 800},
    QualityPreset.PRESENTATION: {"max_width": 1920},
    QualityPreset.PRINT: {"max_width": 3840},
}


@dataclass
class FrameDelay:
    """Per-frame timing control in milliseconds.

    Attributes:
        default_ms: Default delay between frames.
        delays_ms: Per-frame delay overrides keyed by frame index.
        pause_first_ms: Extra pause on the first frame, or ``None``.
        pause_last_ms: Extra pause on the last frame, or ``None``.
    """

    default_ms: int = 100
    delays_ms: dict[int, int] = field(default_factory=dict)
    pause_first_ms: int | None = None
    pause_last_ms: int | None = None

    def resolve(self, n_frames: int) -> list[int]:
        """Compute the delay sequence for *n_frames* frames.

        Returns:
            List of per-frame delays in milliseconds.
        """
        delays = [self.delays_ms.get(i, self.default_ms) for i in range(n_frames)]
        if self.pause_first_ms is not None and delays:
            delays[0] = self.pause_first_ms
        if self.pause_last_ms is not None and delays:
            delays[-1] = self.pause_last_ms
        return delays


@dataclass
class GifConfig:
    """GIF-specific assembly options.

    Attributes:
        loop_count: Number of loops (0 = infinite).
    """

    loop_count: int = 0


@dataclass
class Mp4Config:
    """MP4-specific assembly options.

    Attributes:
        fps: Output frames per second.
        crf: Constant rate factor (lower = higher quality).
        preset: ffmpeg encoding preset.
        pixel_format: Output pixel format.
    """

    fps: float = 10.0
    crf: int = 23
    preset: str = "medium"
    pixel_format: str = "yuv420p"


@dataclass
class MetadataConfig:
    """Optional metadata embedded in the output file.

    Attributes:
        title: Animation title.
        author: Author name.
        comment: Freeform comment string.
    """

    title: str = ""
    author: str = ""
    comment: str = "Generated by tikzgif"


@dataclass
class OutputConfig:
    """Top-level output configuration for animation assembly.

    Attributes:
        format: Target output format.
        output_path: Destination file path.
        preset: Quality preset controlling maximum width.
        frame_delay: Per-frame timing configuration.
        gif: GIF-specific options.
        mp4: MP4-specific options.
        metadata: Metadata to embed in the output.
    """

    format: OutputFormat = OutputFormat.GIF
    output_path: Path = Path("output.gif")
    preset: QualityPreset = QualityPreset.PRESENTATION
    frame_delay: FrameDelay = field(default_factory=FrameDelay)
    gif: GifConfig = field(default_factory=GifConfig)
    mp4: Mp4Config = field(default_factory=Mp4Config)
    metadata: MetadataConfig = field(default_factory=MetadataConfig)


def _run(cmd: list[str], *, timeout: int = 300) -> None:
    """Run a subprocess command with error handling.

    Raises:
        AssemblyError: If the command exits with a non-zero return code.
    """
    try:
        subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.CalledProcessError as exc:
        raise AssemblyError(
            f"Subprocess failed (rc={exc.returncode}): {' '.join(cmd)}\n{exc.stderr}",
            output_format="mp4",
        ) from exc
    except subprocess.TimeoutExpired as exc:
        raise AssemblyError(
            f"Subprocess timed out after {timeout}s: {' '.join(cmd)}",
            output_format="mp4",
        ) from exc


def _load_images(
    frame_results: list[FrameResult],
    cfg: OutputConfig,
) -> tuple[list[Image.Image], list[int]]:
    """Load and optionally downscale successfully rendered frame images.

    Args:
        frame_results: Results from the compilation stage.
        cfg: Output configuration with quality preset and timing.

    Returns:
        Tuple of (RGBA images, per-frame delays in ms).

    Raises:
        AssemblyError: If no successfully compiled frames are available.
    """
    successful = sorted(
        [
            fr
            for fr in frame_results
            if fr.success and fr.png_path and fr.png_path.exists()
        ],
        key=lambda result: result.index,
    )
    if not successful:
        raise AssemblyError(
            "No successfully compiled frames to assemble.",
            output_format=cfg.format.value,
        )

    images = []
    for result in successful:
        with Image.open(result.png_path) as frame:
            images.append(frame.convert("RGBA"))

    delays = cfg.frame_delay.resolve(len(images))

    max_width = QUALITY_PRESETS[cfg.preset]["max_width"]
    if images and images[0].width > max_width:
        scale = max_width / images[0].width
        resized = []
        for image in images:
            new_size = (max_width, int(image.height * scale))
            resized.append(image.resize(new_size, Image.LANCZOS))
        images = resized

    return images, delays


# GIF palettes hold 256 entries (indices 0-255). When the animation needs a
# transparent background the highest index is reserved as the transparency
# slot, leaving 255 colors for image content.
_TRANSPARENT_INDEX = 255
_OPAQUE_PALETTE_COLORS = 256
_TRANSPARENT_PALETTE_COLORS = 255
# Pixels at least this opaque are treated as solid; anything below becomes the
# transparent index. GIF transparency is binary, so a single cutoff is used.
_ALPHA_OPAQUE_THRESHOLD = 128


def _has_transparency(images: list[Image.Image]) -> bool:
    """Return whether any frame contains non-opaque pixels.

    The upstream pipeline composites onto a solid background when one is
    requested, so genuinely transparent pixels only survive when the caller
    asked for a transparent background (``background is None``).
    """
    for image in images:
        # ``getchannel`` yields a single-band image, so ``getextrema`` returns a
        # ``(min, max)`` pair for that band.
        extrema = cast("tuple[int, int]", image.getchannel("A").getextrema())
        if extrema[0] < 255:
            return True
    return False


def _build_master_palette(
    images: list[Image.Image],
    *,
    colors: int,
) -> Image.Image:
    """Build one adaptive palette shared by every frame.

    All frames are stacked into a single image that is quantized once, so the
    resulting palette represents colors from the whole animation and does not
    flicker between frames. Returns a palette-mode image whose palette is
    reused to quantize each frame.
    """
    rgb_frames = [image.convert("RGB") for image in images]
    if len(rgb_frames) == 1:
        montage = rgb_frames[0]
    else:
        width = max(frame.width for frame in rgb_frames)
        total_height = sum(frame.height for frame in rgb_frames)
        montage = Image.new("RGB", (width, total_height))
        offset = 0
        for frame in rgb_frames:
            montage.paste(frame, (0, offset))
            offset += frame.height
    return montage.quantize(colors=colors, method=Image.Quantize.MEDIANCUT)


def _quantize_frames(
    images: list[Image.Image],
    *,
    transparent: bool,
) -> list[Image.Image]:
    """Quantize every frame to one shared palette using Pillow built-ins.

    No per-pixel or per-color Python loops are used. When *transparent* is set,
    the reserved transparency index is written wherever the source alpha falls
    below the opacity threshold.
    """
    colors = _TRANSPARENT_PALETTE_COLORS if transparent else _OPAQUE_PALETTE_COLORS
    master = _build_master_palette(images, colors=colors)

    quantized: list[Image.Image] = []
    for image in images:
        frame = image.convert("RGB").quantize(palette=master, dither=Image.Dither.NONE)
        if transparent:
            # Map sub-threshold alpha onto the reserved transparency index.
            mask = image.getchannel("A").point(
                lambda a: 255 if a < _ALPHA_OPAQUE_THRESHOLD else 0
            )
            frame.paste(_TRANSPARENT_INDEX, (0, 0), mask)
        quantized.append(frame)
    return quantized


class GifAssembler:
    """Assemble PNG frames into an animated GIF.

    Args:
        config: Output configuration with GIF-specific settings.
    """

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        """Write an animated GIF from compiled frame results.

        Args:
            frame_results: Results from the compilation stage.

        Returns:
            Path to the written GIF file.

        Raises:
            AssemblyError: If no frames are available or writing fails.
        """
        images, delays = _load_images(frame_results, self.config)
        output = self.config.output_path

        transparent = _has_transparency(images)
        quantized = _quantize_frames(images, transparent=transparent)
        first = quantized[0]
        rest = quantized[1:]

        save_kwargs: dict[str, Any] = {
            "format": "GIF",
            "save_all": True,
            "append_images": rest,
            "duration": delays,
            "loop": self.config.gif.loop_count,
            "optimize": not transparent,
            "comment": self.config.metadata.comment.encode("utf-8"),
        }
        if transparent:
            # Reserve the final palette slot as the GIF transparency index so
            # the requested transparent background is preserved rather than
            # composited away. ``disposal=2`` clears each frame before the next
            # so transparent regions do not accumulate stale pixels.
            save_kwargs["transparency"] = _TRANSPARENT_INDEX
            save_kwargs["disposal"] = 2

        print(f"\rWriting {output.name}...", end="", flush=True, file=sys.stderr)
        try:
            first.save(output, **save_kwargs)
        except OSError as exc:
            raise AssemblyError(
                f"Failed to write GIF to {output}: {exc}",
                output_format="gif",
            ) from exc
        print(f"\rWriting {output.name}... done", file=sys.stderr)

        return output


class Mp4Assembler:
    """Assemble PNG frames into an MP4 video using ``ffmpeg``.

    Args:
        config: Output configuration with MP4-specific settings.
    """

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        """Write an MP4 video from compiled frame results.

        Args:
            frame_results: Results from the compilation stage.

        Returns:
            Path to the written MP4 file.

        Raises:
            DependencyError: If ``ffmpeg`` is missing from ``$PATH``.
            AssemblyError: If no frames are available or encoding fails.
        """
        if shutil.which("ffmpeg") is None:
            raise DependencyError(
                "ffmpeg not found on PATH. Install ffmpeg to create MP4 output.",
                tool="ffmpeg",
                install_hint=(
                    "macOS: brew install ffmpeg | "
                    "Debian/Ubuntu: sudo apt install ffmpeg | "
                    "Windows: choco install ffmpeg"
                ),
            )

        images, delays = _load_images(frame_results, self.config)
        output = self.config.output_path

        with tempfile.TemporaryDirectory(prefix="tikzgif_mp4_") as tmpdir:
            tmp = Path(tmpdir)
            frame_paths: list[Path] = []
            for idx, image in enumerate(images):
                frame_path = tmp / f"frame_{idx:06d}.png"
                image.save(frame_path, format="PNG")
                frame_paths.append(frame_path)

            # Honor per-frame delays via the concat demuxer. Each entry pairs a
            # frame with its duration in seconds. The demuxer ignores the final
            # entry's duration, so the last frame is listed twice to preserve
            # its intended hold time.
            concat_path = tmp / "frames.txt"
            lines: list[str] = []
            for frame_path, delay_ms in zip(frame_paths, delays, strict=True):
                duration_s = max(delay_ms, 1) / 1000.0
                lines.append(f"file '{frame_path.name}'")
                lines.append(f"duration {duration_s:.6f}")
            # Repeat the last frame (without a duration) so its hold time is not
            # silently dropped by the concat demuxer's final-entry quirk.
            lines.append(f"file '{frame_paths[-1].name}'")
            concat_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

            cmd = [
                "ffmpeg",
                "-y",
                "-f",
                "concat",
                "-safe",
                "0",
                "-i",
                str(concat_path),
                "-an",
                "-c:v",
                "libx264",
                "-crf",
                str(self.config.mp4.crf),
                "-preset",
                self.config.mp4.preset,
                "-pix_fmt",
                self.config.mp4.pixel_format,
                "-vf",
                "pad=ceil(iw/2)*2:ceil(ih/2)*2",
                "-fps_mode",
                "vfr",
                "-movflags",
                "+faststart",
            ]
            if self.config.metadata.title:
                cmd += ["-metadata", f"title={self.config.metadata.title}"]
            if self.config.metadata.author:
                cmd += ["-metadata", f"artist={self.config.metadata.author}"]
            if self.config.metadata.comment:
                cmd += ["-metadata", f"comment={self.config.metadata.comment}"]
            cmd.append(str(output))

            print(f"\rEncoding {output.name}...", end="", flush=True, file=sys.stderr)
            _run(cmd, timeout=600)
            print(f"\rEncoding {output.name}... done", file=sys.stderr)

        return output


class AnimationAssembler:
    """Dispatch to the appropriate format-specific assembler.

    Args:
        config: Output configuration specifying the target format.
    """

    _ASSEMBLERS: ClassVar[
        dict[OutputFormat, type[GifAssembler] | type[Mp4Assembler]]
    ] = {
        OutputFormat.GIF: GifAssembler,
        OutputFormat.MP4: Mp4Assembler,
    }

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        """Assemble frames into the configured output format.

        Args:
            frame_results: Results from the compilation stage.

        Returns:
            Path to the written output file.

        Raises:
            AssemblyError: If the output format is unsupported.
        """
        assembler_cls = self._ASSEMBLERS.get(self.config.format)
        if assembler_cls is None:
            raise AssemblyError(
                f"Unsupported output format: {self.config.format}",
                output_format=str(self.config.format),
            )
        assembler = assembler_cls(self.config)
        return assembler.assemble(frame_results)
