"""Core animation assembly for GIF and MP4 outputs."""

from __future__ import annotations

import enum
import logging
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image

from ..exceptions import AssemblyError
from ..types import FrameResult

logger = logging.getLogger(__name__)


class OutputFormat(enum.Enum):
    """Supported output animation formats."""

    GIF = "gif"
    MP4 = "mp4"


class QualityPreset(enum.Enum):
    """Quality presets controlling maximum output width."""

    WEB = "web"
    PRESENTATION = "presentation"
    PRINT = "print"


QUALITY_PRESETS: dict[QualityPreset, dict[str, int]] = {
    QualityPreset.WEB: {"max_width": 800},
    QualityPreset.PRESENTATION: {"max_width": 1920},
    QualityPreset.PRINT: {"max_width": 3840},
}


@dataclass
class FrameDelay:
    """Per-frame timing control in milliseconds.

    Attributes:
        default_ms: Default delay between frames.
        delays_ms: Per-frame delay overrides keyed by frame index.
        pause_first_ms: Extra pause on the first frame, or ``None``.
        pause_last_ms: Extra pause on the last frame, or ``None``.
    """

    default_ms: int = 100
    delays_ms: dict[int, int] = field(default_factory=dict)
    pause_first_ms: int | None = None
    pause_last_ms: int | None = None

    def resolve(self, n_frames: int) -> list[int]:
        """Compute the delay sequence for *n_frames* frames.

        Returns:
            List of per-frame delays in milliseconds.
        """
        delays = [self.delays_ms.get(i, self.default_ms) for i in range(n_frames)]
        if self.pause_first_ms is not None and delays:
            delays[0] = self.pause_first_ms
        if self.pause_last_ms is not None and delays:
            delays[-1] = self.pause_last_ms
        return delays


@dataclass
class GifConfig:
    """GIF-specific assembly options.

    Attributes:
        loop_count: Number of loops (0 = infinite).
    """

    loop_count: int = 0


@dataclass
class Mp4Config:
    """MP4-specific assembly options.

    Attributes:
        fps: Output frames per second.
        crf: Constant rate factor (lower = higher quality).
        preset: ffmpeg encoding preset.
        pixel_format: Output pixel format.
    """

    fps: float = 10.0
    crf: int = 23
    preset: str = "medium"
    pixel_format: str = "yuv420p"


@dataclass
class MetadataConfig:
    """Optional metadata embedded in the output file.

    Attributes:
        title: Animation title.
        author: Author name.
        comment: Freeform comment string.
    """

    title: str = ""
    author: str = ""
    comment: str = "Generated by tikzgif"


@dataclass
class OutputConfig:
    """Top-level output configuration for animation assembly.

    Attributes:
        format: Target output format.
        output_path: Destination file path.
        preset: Quality preset controlling maximum width.
        frame_delay: Per-frame timing configuration.
        gif: GIF-specific options.
        mp4: MP4-specific options.
        metadata: Metadata to embed in the output.
    """

    format: OutputFormat = OutputFormat.GIF
    output_path: Path = Path("output.gif")
    preset: QualityPreset = QualityPreset.PRESENTATION
    frame_delay: FrameDelay = field(default_factory=FrameDelay)
    gif: GifConfig = field(default_factory=GifConfig)
    mp4: Mp4Config = field(default_factory=Mp4Config)
    metadata: MetadataConfig = field(default_factory=MetadataConfig)


def _run(cmd: list[str], *, timeout: int = 300) -> None:
    """Run a subprocess command with error handling.

    Raises:
        AssemblyError: If the command exits with a non-zero return code.
    """
    try:
        subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.CalledProcessError as exc:
        raise AssemblyError(
            f"Subprocess failed (rc={exc.returncode}): {' '.join(cmd)}\n"
            f"{exc.stderr}",
            output_format="mp4",
        ) from exc
    except subprocess.TimeoutExpired as exc:
        raise AssemblyError(
            f"Subprocess timed out after {timeout}s: {' '.join(cmd)}",
            output_format="mp4",
        ) from exc


def _load_images(
    frame_results: list[FrameResult],
    cfg: OutputConfig,
) -> tuple[list[Image.Image], list[int]]:
    """Load and optionally downscale successfully rendered frame images.

    Args:
        frame_results: Results from the compilation stage.
        cfg: Output configuration with quality preset and timing.

    Returns:
        Tuple of (RGBA images, per-frame delays in ms).

    Raises:
        AssemblyError: If no successfully compiled frames are available.
    """
    successful = sorted(
        [fr for fr in frame_results if fr.success and fr.png_path and fr.png_path.exists()],
        key=lambda result: result.index,
    )
    if not successful:
        raise AssemblyError(
            "No successfully compiled frames to assemble.",
            output_format=cfg.format.value,
        )

    images = []
    for result in successful:
        with Image.open(result.png_path) as frame:
            images.append(frame.convert("RGBA"))

    delays = cfg.frame_delay.resolve(len(images))

    max_width = QUALITY_PRESETS[cfg.preset]["max_width"]
    if images and images[0].width > max_width:
        scale = max_width / images[0].width
        resized = []
        for image in images:
            new_size = (max_width, int(image.height * scale))
            resized.append(image.resize(new_size, Image.LANCZOS))
        images = resized

    return images, delays


class GifAssembler:
    """Assemble PNG frames into an animated GIF.

    Args:
        config: Output configuration with GIF-specific settings.
    """

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        """Write an animated GIF from compiled frame results.

        Args:
            frame_results: Results from the compilation stage.

        Returns:
            Path to the written GIF file.

        Raises:
            AssemblyError: If no frames are available or writing fails.
        """
        images, delays = _load_images(frame_results, self.config)
        output = self.config.output_path

        total = len(images)

        # Step 1: Scan color frequencies across all frames
        from collections import Counter
        color_counts: Counter[tuple[int, int, int]] = Counter()
        for i, img in enumerate(images):
            rgb = img.convert("RGB")
            color_counts.update(rgb.getdata())
            pct = ((i + 1) / total) * 100
            print(
                f"\rScanning colors: {i + 1}/{total} ({pct:.0f}%) — {len(color_counts)} unique",
                end="", flush=True, file=sys.stderr,
            )
        print(file=sys.stderr)

        n_unique = len(color_counts)
        total_pixels = sum(color_counts.values())

        # Step 2: Build palette from top 256 most frequent colors
        if n_unique <= 256:
            palette_colors = sorted(color_counts.keys())
            remapped = 0
            print(
                f"Building palette: {n_unique} unique colors — exact fit, no quantization needed",
                file=sys.stderr,
            )
        else:
            palette_colors = [c for c, _ in color_counts.most_common(256)]
            top256_pixels = sum(color_counts[c] for c in palette_colors)
            coverage = (top256_pixels / total_pixels) * 100
            remapped = n_unique - 256
            print(
                f"Building palette: {n_unique} unique colors -> top 256 by frequency "
                f"({coverage:.2f}% pixel coverage, {remapped} rare colors remapped)",
                file=sys.stderr,
            )

        # Build lookup: palette index for each color
        color_to_idx = {c: i for i, c in enumerate(palette_colors)}

        # For colors not in the palette, find nearest neighbor
        if n_unique > 256:
            palette_arr = palette_colors  # list for distance calc
            for color in color_counts:
                if color not in color_to_idx:
                    # Find nearest palette color by squared Euclidean distance
                    best_idx = 0
                    best_dist = float("inf")
                    r0, g0, b0 = color
                    for idx, (r1, g1, b1) in enumerate(palette_arr):
                        d = (r0 - r1) ** 2 + (g0 - g1) ** 2 + (b0 - b1) ** 2
                        if d < best_dist:
                            best_dist = d
                            best_idx = idx
                    color_to_idx[color] = best_idx

        flat_palette: list[int] = []
        for r, g, b in palette_colors:
            flat_palette.extend((r, g, b))
        flat_palette.extend([0] * (768 - len(flat_palette)))

        # Step 3: Quantize frames using the palette
        quantized = []
        for i, img in enumerate(images):
            rgb = img.convert("RGB")
            p_img = Image.new("P", rgb.size)
            p_img.putpalette(flat_palette)
            p_img.putdata([color_to_idx[px] for px in rgb.getdata()])
            quantized.append(p_img)
            pct = ((i + 1) / total) * 100
            print(
                f"\rQuantizing: {i + 1}/{total} ({pct:.0f}%)",
                end="", flush=True, file=sys.stderr,
            )

        print(file=sys.stderr)
        first = quantized[0]
        rest = quantized[1:]

        print(f"\rWriting {output.name}...", end="", flush=True, file=sys.stderr)
        try:
            first.save(
                output,
                format="GIF",
                save_all=True,
                append_images=rest,
                duration=delays,
                loop=self.config.gif.loop_count,
                optimize=True,
                comment=self.config.metadata.comment.encode("utf-8"),
            )
        except OSError as exc:
            raise AssemblyError(
                f"Failed to write GIF to {output}: {exc}",
                output_format="gif",
            ) from exc
        print(f"\rWriting {output.name}... done", file=sys.stderr)

        return output


class Mp4Assembler:
    """Assemble PNG frames into an MP4 video using ``ffmpeg``.

    Args:
        config: Output configuration with MP4-specific settings.
    """

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        """Write an MP4 video from compiled frame results.

        Args:
            frame_results: Results from the compilation stage.

        Returns:
            Path to the written MP4 file.

        Raises:
            AssemblyError: If ``ffmpeg`` is missing, no frames are
                available, or encoding fails.
        """
        if shutil.which("ffmpeg") is None:
            raise AssemblyError(
                "ffmpeg not found on PATH. Install ffmpeg to create MP4 output.",
                output_format="mp4",
            )

        images, _delays = _load_images(frame_results, self.config)
        output = self.config.output_path

        with tempfile.TemporaryDirectory(prefix="tikzgif_mp4_") as tmpdir:
            tmp = Path(tmpdir)
            for idx, image in enumerate(images):
                image.save(tmp / f"frame_{idx:06d}.png", format="PNG")

            cmd = [
                "ffmpeg",
                "-y",
                "-framerate",
                str(self.config.mp4.fps),
                "-i",
                str(tmp / "frame_%06d.png"),
                "-an",
                "-c:v",
                "libx264",
                "-crf",
                str(self.config.mp4.crf),
                "-preset",
                self.config.mp4.preset,
                "-pix_fmt",
                self.config.mp4.pixel_format,
                "-vf",
                "pad=ceil(iw/2)*2:ceil(ih/2)*2",
                "-movflags",
                "+faststart",
            ]
            if self.config.metadata.title:
                cmd += ["-metadata", f"title={self.config.metadata.title}"]
            if self.config.metadata.author:
                cmd += ["-metadata", f"artist={self.config.metadata.author}"]
            if self.config.metadata.comment:
                cmd += ["-metadata", f"comment={self.config.metadata.comment}"]
            cmd.append(str(output))

            print(f"\rEncoding {output.name}...", end="", flush=True, file=sys.stderr)
            _run(cmd, timeout=600)
            print(f"\rEncoding {output.name}... done", file=sys.stderr)

        return output


class AnimationAssembler:
    """Dispatch to the appropriate format-specific assembler.

    Args:
        config: Output configuration specifying the target format.
    """

    _ASSEMBLERS: dict[OutputFormat, type[GifAssembler] | type[Mp4Assembler]] = {
        OutputFormat.GIF: GifAssembler,
        OutputFormat.MP4: Mp4Assembler,
    }

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        """Assemble frames into the configured output format.

        Args:
            frame_results: Results from the compilation stage.

        Returns:
            Path to the written output file.

        Raises:
            AssemblyError: If the output format is unsupported.
        """
        assembler_cls = self._ASSEMBLERS.get(self.config.format)
        if assembler_cls is None:
            raise AssemblyError(
                f"Unsupported output format: {self.config.format}",
                output_format=str(self.config.format),
            )
        assembler = assembler_cls(self.config)
        return assembler.assemble(frame_results)
