"""Core animation assembly for GIF and MP4 outputs."""

from __future__ import annotations

import enum
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image

from .types import FrameResult


class OutputFormat(enum.Enum):
    """Supported output formats."""

    GIF = "gif"
    MP4 = "mp4"


class QualityPreset(enum.Enum):
    """Quality presets used for output scaling."""

    WEB = "web"
    PRESENTATION = "presentation"
    PRINT = "print"


QUALITY_PRESETS: dict[QualityPreset, dict[str, int]] = {
    QualityPreset.WEB: {"max_width": 800},
    QualityPreset.PRESENTATION: {"max_width": 1920},
    QualityPreset.PRINT: {"max_width": 3840},
}


@dataclass
class FrameDelay:
    """Per-frame timing control in milliseconds."""

    default_ms: int = 100
    delays_ms: dict[int, int] = field(default_factory=dict)
    pause_first_ms: int | None = None
    pause_last_ms: int | None = None

    def resolve(self, n_frames: int) -> list[int]:
        delays = [self.delays_ms.get(i, self.default_ms) for i in range(n_frames)]
        if self.pause_first_ms is not None and delays:
            delays[0] = self.pause_first_ms
        if self.pause_last_ms is not None and delays:
            delays[-1] = self.pause_last_ms
        return delays


@dataclass
class GifConfig:
    """GIF assembly options."""

    loop_count: int = 0


@dataclass
class Mp4Config:
    """MP4 assembly options."""

    fps: float = 10.0
    crf: int = 23
    preset: str = "medium"
    pixel_format: str = "yuv420p"


@dataclass
class MetadataConfig:
    """Optional metadata."""

    title: str = ""
    author: str = ""
    comment: str = "Generated by tikzgif"


@dataclass
class OutputConfig:
    """Top-level output configuration."""

    format: OutputFormat = OutputFormat.GIF
    output_path: Path = Path("output.gif")
    preset: QualityPreset = QualityPreset.PRESENTATION
    frame_delay: FrameDelay = field(default_factory=FrameDelay)
    gif: GifConfig = field(default_factory=GifConfig)
    mp4: Mp4Config = field(default_factory=Mp4Config)
    metadata: MetadataConfig = field(default_factory=MetadataConfig)


def _run(cmd: list[str], *, timeout: int = 300) -> None:
    subprocess.run(
        cmd,
        check=True,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def _load_images(
    frame_results: list[FrameResult],
    cfg: OutputConfig,
) -> tuple[list[Image.Image], list[int]]:
    successful = sorted(
        [fr for fr in frame_results if fr.success and fr.png_path and fr.png_path.exists()],
        key=lambda result: result.index,
    )
    if not successful:
        raise ValueError("No successfully compiled frames to assemble")

    images = []
    for result in successful:
        with Image.open(result.png_path) as frame:
            images.append(frame.convert("RGBA"))

    delays = cfg.frame_delay.resolve(len(images))

    max_width = QUALITY_PRESETS[cfg.preset]["max_width"]
    if images and images[0].width > max_width:
        scale = max_width / images[0].width
        resized = []
        for image in images:
            new_size = (max_width, int(image.height * scale))
            resized.append(image.resize(new_size, Image.LANCZOS))
        images = resized

    return images, delays


class GifAssembler:
    """Assemble PNG frames into an animated GIF."""

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        images, delays = _load_images(frame_results, self.config)
        output = self.config.output_path

        first = images[0].convert("P", palette=Image.Palette.ADAPTIVE)
        rest = [img.convert("P", palette=Image.Palette.ADAPTIVE) for img in images[1:]]
        first.save(
            output,
            format="GIF",
            save_all=True,
            append_images=rest,
            duration=delays,
            loop=self.config.gif.loop_count,
            optimize=True,
            comment=self.config.metadata.comment.encode("utf-8"),
        )
        return output


class Mp4Assembler:
    """Assemble PNG frames into MP4 using ffmpeg."""

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        if shutil.which("ffmpeg") is None:
            raise RuntimeError("ffmpeg not found. Install ffmpeg to create MP4 output.")

        images, _delays = _load_images(frame_results, self.config)
        output = self.config.output_path

        with tempfile.TemporaryDirectory(prefix="tikzgif_mp4_") as tmpdir:
            tmp = Path(tmpdir)
            for idx, image in enumerate(images):
                image.save(tmp / f"frame_{idx:06d}.png", format="PNG")

            cmd = [
                "ffmpeg",
                "-y",
                "-framerate",
                str(self.config.mp4.fps),
                "-i",
                str(tmp / "frame_%06d.png"),
                "-an",
                "-c:v",
                "libx264",
                "-crf",
                str(self.config.mp4.crf),
                "-preset",
                self.config.mp4.preset,
                "-pix_fmt",
                self.config.mp4.pixel_format,
                "-vf",
                "pad=ceil(iw/2)*2:ceil(ih/2)*2",
                "-movflags",
                "+faststart",
            ]
            if self.config.metadata.title:
                cmd += ["-metadata", f"title={self.config.metadata.title}"]
            if self.config.metadata.author:
                cmd += ["-metadata", f"artist={self.config.metadata.author}"]
            if self.config.metadata.comment:
                cmd += ["-metadata", f"comment={self.config.metadata.comment}"]
            cmd.append(str(output))

            _run(cmd, timeout=600)

        return output


class AnimationAssembler:
    """Dispatch to format-specific assemblers."""

    _ASSEMBLERS: dict[OutputFormat, type[GifAssembler] | type[Mp4Assembler]] = {
        OutputFormat.GIF: GifAssembler,
        OutputFormat.MP4: Mp4Assembler,
    }

    def __init__(self, config: OutputConfig) -> None:
        self.config = config

    def assemble(self, frame_results: list[FrameResult]) -> Path:
        assembler_cls = self._ASSEMBLERS.get(self.config.format)
        if assembler_cls is None:
            raise ValueError(f"Unsupported output format: {self.config.format}")
        assembler = assembler_cls(self.config)
        return assembler.assemble(frame_results)
