"""Pipeline configuration objects for tikzgif.

Dataclasses providing explicit stage-level configuration with
backward-compatible adapters for the legacy ``render()`` API.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .assembly import (
    FrameDelay,
    OutputConfig as AssemblyOutputConfig,
    OutputFormat,
    QualityPreset,
)
from .backends import ColorSpace, RenderConfig
from .types import BoundingBox, CompilationConfig, ErrorPolicy, LatexEngine


@dataclass(frozen=True)
class TemplateConfig:
    """Template parsing and substitution settings.

    Attributes:
        param_token: Token to substitute (e.g. ``"\\PARAM"``).
        extra_preamble: Additional LaTeX preamble lines to inject.
        enforced_bbox: Fixed bounding box to inject, or ``None``.
    """

    param_token: str = r"\PARAM"
    extra_preamble: str = ""
    enforced_bbox: BoundingBox | None = None


@dataclass(frozen=True)
class CompileConfig:
    """LaTeX compilation settings.

    Attributes:
        engine: LaTeX engine, or ``None`` for auto-detection.
        error_policy: Strategy for handling frame failures.
        max_workers: Number of parallel workers (0 = auto).
        shell_escape: Whether to enable ``--shell-escape``.
        extra_args: Additional arguments forwarded to the engine.
        cache_dir: Custom cache root, or ``None`` for platform default.
        timeout_per_frame_s: Maximum seconds per frame compilation.
        dpi: Target DPI for rasterization.
    """

    engine: LatexEngine | None = None
    error_policy: ErrorPolicy = ErrorPolicy.RETRY
    max_workers: int = 0
    shell_escape: bool = False
    extra_args: tuple[str, ...] = ()
    cache_dir: Path | None = None
    timeout_per_frame_s: float = 30.0
    dpi: int = 300
    no_cache: bool = False

    def to_compilation_config(self) -> CompilationConfig:
        """Convert to the compile engine's internal ``CompilationConfig``."""
        return CompilationConfig(
            engine=self.engine,
            error_policy=self.error_policy,
            max_workers=self.max_workers,
            shell_escape=self.shell_escape,
            extra_args=list(self.extra_args),
            cache_dir=self.cache_dir,
            timeout_per_frame_s=self.timeout_per_frame_s,
            dpi=self.dpi,
            no_cache=self.no_cache,
        )


@dataclass(frozen=True)
class RasterConfig:
    """PDF-to-image rasterization settings.

    Attributes:
        backend: Backend name (e.g. ``"pdftoppm"``).
        dpi: Target DPI.
        color_space: Output color space.
        background: Background color, or ``None`` for transparency.
        antialias: Whether to enable supersampled anti-aliasing.
        antialias_factor: Supersampling multiplier.
        threads: Number of rendering threads.
    """

    backend: str = "pdftoppm"
    dpi: int = 300
    color_space: ColorSpace = ColorSpace.RGBA
    background: str | None = "white"
    antialias: bool = False
    antialias_factor: int = 2
    threads: int = 1

    def to_render_config(self) -> RenderConfig:
        """Convert to a raster backend ``RenderConfig``."""
        return RenderConfig(
            dpi=self.dpi,
            color_space=self.color_space,
            background=self.background,
            antialias=self.antialias,
            antialias_factor=self.antialias_factor,
            threads=self.threads,
        )


@dataclass(frozen=True)
class OutputConfig:
    """Output assembly settings shared by GIF and MP4.

    Attributes:
        format: Target output format.
        quality: Quality preset controlling maximum width.
        fps: Frames per second.
        output_path: Explicit output path, or ``None`` for auto.
        raw_pdf_dir: Directory to copy raw PDFs, or ``None``.
        raw_png_dir: Directory to copy raw PNGs, or ``None``.
        gif_loop_count: GIF loop count (0 = infinite).
        mp4_crf: MP4 constant rate factor.
        mp4_preset: ffmpeg encoding preset.
        mp4_pixel_format: MP4 pixel format.
        metadata_title: Output file title.
        metadata_author: Output file author.
        metadata_comment: Output file comment.
        frame_delay_default_ms: Default inter-frame delay in ms.
        frame_delay_overrides_ms: Per-frame delay overrides.
        pause_first_ms: Pause on first frame in ms.
        pause_last_ms: Pause on last frame in ms.
    """

    format: OutputFormat = OutputFormat.GIF
    quality: QualityPreset = QualityPreset.PRESENTATION
    fps: int = 30
    output_path: Path | None = None
    raw_pdf_dir: Path | None = None
    raw_png_dir: Path | None = None

    gif_loop_count: int = 0
    mp4_crf: int = 23
    mp4_preset: str = "medium"
    mp4_pixel_format: str = "yuv420p"

    metadata_title: str = ""
    metadata_author: str = ""
    metadata_comment: str = "Generated by tikzgif"

    frame_delay_default_ms: int | None = None
    frame_delay_overrides_ms: dict[int, int] = field(default_factory=dict)
    pause_first_ms: int | None = None
    pause_last_ms: int | None = None

    def to_assembly_config(self, default_output_path: Path) -> AssemblyOutputConfig:
        """Convert to the assembly module's ``OutputConfig``."""
        output_cfg = AssemblyOutputConfig(
            format=self.format,
            output_path=self.output_path or default_output_path,
            preset=self.quality,
            frame_delay=FrameDelay(
                default_ms=self.frame_delay_default_ms
                if self.frame_delay_default_ms is not None
                else (int(1000 / self.fps) if self.fps > 0 else 100),
                delays_ms=self.frame_delay_overrides_ms,
                pause_first_ms=self.pause_first_ms,
                pause_last_ms=self.pause_last_ms,
            ),
        )
        output_cfg.gif.loop_count = self.gif_loop_count
        output_cfg.mp4.fps = float(self.fps)
        output_cfg.mp4.crf = self.mp4_crf
        output_cfg.mp4.preset = self.mp4_preset
        output_cfg.mp4.pixel_format = self.mp4_pixel_format
        output_cfg.metadata.title = self.metadata_title
        output_cfg.metadata.author = self.metadata_author
        output_cfg.metadata.comment = self.metadata_comment
        return output_cfg


@dataclass(frozen=True)
class RenderJobConfig:
    """Top-level render job configuration composed of stage configs.

    Attributes:
        tex_file: Path to the ``.tex`` template file.
        start: Starting parameter value.
        end: Ending parameter value.
        frames: Number of animation frames.
        template: Template parsing settings.
        compile: Compilation settings.
        raster: Rasterization settings.
        output: Output assembly settings.
    """

    tex_file: Path
    start: float = 0.0
    end: float = 1.0
    frames: int = 90

    template: TemplateConfig = field(default_factory=TemplateConfig)
    compile: CompileConfig = field(default_factory=CompileConfig)
    raster: RasterConfig = field(default_factory=RasterConfig)
    output: OutputConfig = field(default_factory=OutputConfig)

    def param_values(self) -> list[float]:
        """Return the frame parameter sweep values.

        Returns:
            List of linearly spaced values from *start* to *end*.

        Raises:
            ValueError: If *frames* is less than 1.
        """
        if self.frames <= 0:
            raise ValueError("frames must be >= 1")
        if self.frames == 1:
            return [self.start]
        return [
            self.start + i * (self.end - self.start) / (self.frames - 1)
            for i in range(self.frames)
        ]


def _parse_color_space(color_space: str) -> ColorSpace:
    """Parse a color-space string into a ``ColorSpace`` enum member.

    Args:
        color_space: One of ``"rgb"``, ``"rgba"``, ``"grayscale"``.

    Raises:
        ValueError: If the string is not recognized.
    """
    lowered = color_space.strip().lower()
    if lowered == "rgb":
        return ColorSpace.RGB
    if lowered == "rgba":
        return ColorSpace.RGBA
    if lowered in {"gray", "grayscale", "greyscale"}:
        return ColorSpace.GRAYSCALE
    raise ValueError(
        "Unsupported color_space "
        f"'{color_space}'. Use one of: rgb, rgba, grayscale."
    )


def legacy_args_to_job_config(
    tex_file: str | Path,
    *,
    param: str = "PARAM",
    start: float = 0.0,
    end: float = 1.0,
    frames: int = 90,
    fps: int = 30,
    format: str = "gif",
    quality: str = "presentation",
    engine: str | None = None,
    workers: int = 0,
    timeout: float = 30.0,
    dpi: int = 300,
    error_policy: str = "retry",
    output: str | Path | None = None,
    raw_pdf_dir: str | Path | None = None,
    raw_png_dir: str | Path | None = None,
    bbox: tuple[float, float, float, float] | None = None,
    shell_escape: bool = False,
    latex_args: list[str] | tuple[str, ...] | None = None,
    cache_dir: str | Path | None = None,
    no_cache: bool = False,
    backend: str = "pdftoppm",
    color_space: str = "rgba",
    background: str | None = "white",
    antialias: bool = False,
    antialias_factor: int = 2,
    raster_threads: int = 1,
    gif_loop_count: int = 0,
    mp4_crf: int = 23,
    mp4_preset: str = "medium",
    mp4_pixel_format: str = "yuv420p",
    metadata_title: str = "",
    metadata_author: str = "",
    metadata_comment: str = "Generated by tikzgif",
    frame_delay_default_ms: int | None = None,
    pause_first_ms: int | None = None,
    pause_last_ms: int | None = None,
) -> RenderJobConfig:
    """Build a ``RenderJobConfig`` from legacy ``render()`` keyword arguments.

    Args:
        tex_file: Path to the ``.tex`` template.
        param: Parameter token name (without leading backslash).
        start: Starting parameter value.
        end: Ending parameter value.
        frames: Number of frames.
        fps: Output frames per second.
        format: Output format (``"gif"`` or ``"mp4"``).
        quality: Quality preset name.
        engine: LaTeX engine name, or ``None`` for auto.
        workers: Parallel worker count (0 = auto).
        timeout: Per-frame timeout in seconds.
        dpi: Target DPI.
        error_policy: Error handling strategy name.
        output: Explicit output path, or ``None``.
        raw_pdf_dir: Directory for raw PDFs, or ``None``.
        raw_png_dir: Directory for raw PNGs, or ``None``.
        bbox: Fixed bounding box tuple, or ``None``.
        shell_escape: Whether to enable ``--shell-escape``.
        latex_args: Extra LaTeX engine arguments.
        cache_dir: Custom cache directory, or ``None``.
        backend: Raster backend name.
        color_space: Target color space name.
        background: Background color, or ``None``.
        antialias: Whether to enable supersampled anti-aliasing.
        antialias_factor: Supersampling multiplier.
        raster_threads: Number of rasterization threads.
        gif_loop_count: GIF loop count.
        mp4_crf: MP4 constant rate factor.
        mp4_preset: ffmpeg encoding preset.
        mp4_pixel_format: MP4 pixel format.
        metadata_title: Output title metadata.
        metadata_author: Output author metadata.
        metadata_comment: Output comment metadata.
        frame_delay_default_ms: Default inter-frame delay in ms.
        pause_first_ms: First-frame pause in ms.
        pause_last_ms: Last-frame pause in ms.

    Returns:
        A fully constructed ``RenderJobConfig``.

    Raises:
        ValueError: If any string argument is not a recognized option.
    """
    format_map = {
        "gif": OutputFormat.GIF,
        "mp4": OutputFormat.MP4,
    }
    quality_map = {
        "web": QualityPreset.WEB,
        "presentation": QualityPreset.PRESENTATION,
        "print": QualityPreset.PRINT,
    }
    engine_map = {
        "pdflatex": LatexEngine.PDFLATEX,
        "xelatex": LatexEngine.XELATEX,
        "lualatex": LatexEngine.LUALATEX,
    }
    policy_map = {
        "abort": ErrorPolicy.ABORT,
        "skip": ErrorPolicy.SKIP,
        "retry": ErrorPolicy.RETRY,
    }

    if format not in format_map:
        raise ValueError(f"Unsupported format '{format}'. Use 'gif' or 'mp4'.")
    if quality not in quality_map:
        raise ValueError(
            f"Unsupported quality '{quality}'. Use one of: {', '.join(quality_map)}."
        )
    if error_policy not in policy_map:
        raise ValueError(
            "Unsupported error_policy "
            f"'{error_policy}'. Use one of: {', '.join(policy_map)}."
        )

    enforced_bbox: BoundingBox | None = None
    if bbox is not None:
        enforced_bbox = BoundingBox(
            x_min=bbox[0],
            y_min=bbox[1],
            x_max=bbox[2],
            y_max=bbox[3],
        )

    return RenderJobConfig(
        tex_file=Path(tex_file),
        start=start,
        end=end,
        frames=frames,
        template=TemplateConfig(
            param_token="\\" + param,
            enforced_bbox=enforced_bbox,
        ),
        compile=CompileConfig(
            engine=engine_map.get(engine) if engine else None,
            error_policy=policy_map[error_policy],
            max_workers=workers,
            shell_escape=shell_escape,
            extra_args=tuple(latex_args or ()),
            cache_dir=Path(cache_dir) if cache_dir else None,
            no_cache=no_cache,
            timeout_per_frame_s=timeout,
            dpi=dpi,
        ),
        raster=RasterConfig(
            backend=backend,
            dpi=dpi,
            color_space=_parse_color_space(color_space),
            background=background,
            antialias=antialias,
            antialias_factor=antialias_factor,
            threads=raster_threads,
        ),
        output=OutputConfig(
            format=format_map[format],
            quality=quality_map[quality],
            fps=fps,
            output_path=Path(output) if output else None,
            raw_pdf_dir=Path(raw_pdf_dir) if raw_pdf_dir else None,
            raw_png_dir=Path(raw_png_dir) if raw_png_dir else None,
            gif_loop_count=gif_loop_count,
            mp4_crf=mp4_crf,
            mp4_preset=mp4_preset,
            mp4_pixel_format=mp4_pixel_format,
            metadata_title=metadata_title,
            metadata_author=metadata_author,
            metadata_comment=metadata_comment,
            frame_delay_default_ms=frame_delay_default_ms,
            pause_first_ms=pause_first_ms,
            pause_last_ms=pause_last_ms,
        ),
    )
