"""Pipeline configuration objects for tikzgif.

These dataclasses provide explicit stage-level configuration while
keeping backward-compatible adapters for the legacy ``render(...)`` API.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .assembly import (
    FrameDelay,
    OutputConfig as AssemblyOutputConfig,
    OutputFormat,
    QualityPreset,
)
from .backends import ColorSpace, RenderConfig
from .types import BoundingBox, CompilationConfig, ErrorPolicy, LatexEngine


@dataclass(frozen=True)
class TemplateConfig:
    """Template parsing/substitution settings."""

    param_token: str = r"\PARAM"
    extra_preamble: str = ""
    enforced_bbox: BoundingBox | None = None


@dataclass(frozen=True)
class CompileConfig:
    """LaTeX compilation settings."""

    engine: LatexEngine | None = None
    error_policy: ErrorPolicy = ErrorPolicy.RETRY
    max_workers: int = 0
    shell_escape: bool = False
    extra_args: tuple[str, ...] = ()
    cache_dir: Path | None = None
    timeout_per_frame_s: float = 30.0
    dpi: int = 300

    def to_compilation_config(self) -> CompilationConfig:
        """Convert to the compile engine's internal config dataclass."""
        return CompilationConfig(
            engine=self.engine,
            error_policy=self.error_policy,
            max_workers=self.max_workers,
            shell_escape=self.shell_escape,
            extra_args=list(self.extra_args),
            cache_dir=self.cache_dir,
            timeout_per_frame_s=self.timeout_per_frame_s,
            dpi=self.dpi,
        )


@dataclass(frozen=True)
class RasterConfig:
    """PDF-to-image rasterization settings."""

    backend: str = "pdftoppm"
    dpi: int = 300
    color_space: ColorSpace = ColorSpace.RGBA
    background: str | None = "white"
    antialias: bool = False
    antialias_factor: int = 2
    threads: int = 1

    def to_render_config(self) -> RenderConfig:
        """Convert to raster backend render config."""
        return RenderConfig(
            dpi=self.dpi,
            color_space=self.color_space,
            background=self.background,
            antialias=self.antialias,
            antialias_factor=self.antialias_factor,
            threads=self.threads,
        )


@dataclass(frozen=True)
class OutputConfig:
    """Output assembly settings shared by GIF/MP4."""

    format: OutputFormat = OutputFormat.GIF
    quality: QualityPreset = QualityPreset.PRESENTATION
    fps: int = 30
    output_path: Path | None = None
    raw_pdf_dir: Path | None = None
    raw_png_dir: Path | None = None

    gif_loop_count: int = 0
    mp4_crf: int = 23
    mp4_preset: str = "medium"
    mp4_pixel_format: str = "yuv420p"

    metadata_title: str = ""
    metadata_author: str = ""
    metadata_comment: str = "Generated by tikzgif"

    frame_delay_default_ms: int | None = None
    frame_delay_overrides_ms: dict[int, int] = field(default_factory=dict)
    pause_first_ms: int | None = None
    pause_last_ms: int | None = None

    def to_assembly_config(self, default_output_path: Path) -> AssemblyOutputConfig:
        """Convert to the assembly module config."""
        output_cfg = AssemblyOutputConfig(
            format=self.format,
            output_path=self.output_path or default_output_path,
            preset=self.quality,
            frame_delay=FrameDelay(
                default_ms=self.frame_delay_default_ms
                if self.frame_delay_default_ms is not None
                else (int(1000 / self.fps) if self.fps > 0 else 100),
                delays_ms=self.frame_delay_overrides_ms,
                pause_first_ms=self.pause_first_ms,
                pause_last_ms=self.pause_last_ms,
            ),
        )
        output_cfg.gif.loop_count = self.gif_loop_count
        output_cfg.mp4.fps = float(self.fps)
        output_cfg.mp4.crf = self.mp4_crf
        output_cfg.mp4.preset = self.mp4_preset
        output_cfg.mp4.pixel_format = self.mp4_pixel_format
        output_cfg.metadata.title = self.metadata_title
        output_cfg.metadata.author = self.metadata_author
        output_cfg.metadata.comment = self.metadata_comment
        return output_cfg


@dataclass(frozen=True)
class RenderJobConfig:
    """Top-level render job configuration composed by stage configs."""

    tex_file: Path
    start: float = 0.0
    end: float = 1.0
    frames: int = 90

    template: TemplateConfig = field(default_factory=TemplateConfig)
    compile: CompileConfig = field(default_factory=CompileConfig)
    raster: RasterConfig = field(default_factory=RasterConfig)
    output: OutputConfig = field(default_factory=OutputConfig)

    def param_values(self) -> list[float]:
        """Return the frame parameter sweep values."""
        if self.frames <= 0:
            raise ValueError("frames must be >= 1")
        if self.frames == 1:
            return [self.start]
        return [
            self.start + i * (self.end - self.start) / (self.frames - 1)
            for i in range(self.frames)
        ]


def _parse_color_space(color_space: str) -> ColorSpace:
    lowered = color_space.strip().lower()
    if lowered == "rgb":
        return ColorSpace.RGB
    if lowered == "rgba":
        return ColorSpace.RGBA
    if lowered in {"gray", "grayscale", "greyscale"}:
        return ColorSpace.GRAYSCALE
    raise ValueError(
        "Unsupported color_space "
        f"'{color_space}'. Use one of: rgb, rgba, grayscale."
    )


def legacy_args_to_job_config(
    tex_file: str | Path,
    *,
    param: str = "PARAM",
    start: float = 0.0,
    end: float = 1.0,
    frames: int = 90,
    fps: int = 30,
    format: str = "gif",
    quality: str = "presentation",
    engine: str | None = None,
    workers: int = 0,
    timeout: float = 30.0,
    dpi: int = 300,
    error_policy: str = "retry",
    output: str | Path | None = None,
    raw_pdf_dir: str | Path | None = None,
    raw_png_dir: str | Path | None = None,
    bbox: tuple[float, float, float, float] | None = None,
) -> RenderJobConfig:
    """Build explicit job config from legacy ``render(...)`` kwargs."""

    format_map = {
        "gif": OutputFormat.GIF,
        "mp4": OutputFormat.MP4,
    }
    quality_map = {
        "web": QualityPreset.WEB,
        "presentation": QualityPreset.PRESENTATION,
        "print": QualityPreset.PRINT,
    }
    engine_map = {
        "pdflatex": LatexEngine.PDFLATEX,
        "xelatex": LatexEngine.XELATEX,
        "lualatex": LatexEngine.LUALATEX,
    }
    policy_map = {
        "abort": ErrorPolicy.ABORT,
        "skip": ErrorPolicy.SKIP,
        "retry": ErrorPolicy.RETRY,
    }

    if format not in format_map:
        raise ValueError(f"Unsupported format '{format}'. Use 'gif' or 'mp4'.")
    if quality not in quality_map:
        raise ValueError(
            f"Unsupported quality '{quality}'. Use one of: {', '.join(quality_map)}."
        )
    if error_policy not in policy_map:
        raise ValueError(
            "Unsupported error_policy "
            f"'{error_policy}'. Use one of: {', '.join(policy_map)}."
        )

    enforced_bbox: BoundingBox | None = None
    if bbox is not None:
        enforced_bbox = BoundingBox(
            x_min=bbox[0],
            y_min=bbox[1],
            x_max=bbox[2],
            y_max=bbox[3],
        )

    return RenderJobConfig(
        tex_file=Path(tex_file),
        start=start,
        end=end,
        frames=frames,
        template=TemplateConfig(
            param_token="\\" + param,
            enforced_bbox=enforced_bbox,
        ),
        compile=CompileConfig(
            engine=engine_map.get(engine) if engine else None,
            error_policy=policy_map[error_policy],
            max_workers=workers,
            timeout_per_frame_s=timeout,
            dpi=dpi,
        ),
        raster=RasterConfig(
            backend="pdftoppm",
            dpi=dpi,
            color_space=_parse_color_space("rgba"),
            background="white",
            antialias=False,
            threads=1,
        ),
        output=OutputConfig(
            format=format_map[format],
            quality=quality_map[quality],
            fps=fps,
            output_path=Path(output) if output else None,
            raw_pdf_dir=Path(raw_pdf_dir) if raw_pdf_dir else None,
            raw_png_dir=Path(raw_png_dir) if raw_png_dir else None,
        ),
    )
