name: Bug Report
description: Report a bug in tikzgif
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Create a .tex file with ...
        2. Run `tikzgif render file.tex ...`
        3. Observe error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include the full traceback if applicable.
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 14.5 / Ubuntu 24.04 / Windows 11"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "3.12.3"
    validations:
      required: true

  - type: input
    id: tikzgif-version
    attributes:
      label: tikzgif version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: latex
    attributes:
      label: LaTeX distribution
      placeholder: "TeX Live 2024 / MiKTeX 24.1"
    validations:
      required: false

  - type: textarea
    id: tex-file
    attributes:
      label: Minimal .tex file
      description: If the bug involves compilation, paste a minimal .tex file that triggers it.
      render: latex
    validations:
      required: false
